import {StyleSheet} from "react-native";

export const styles = StyleSheet.create({
	container: {
		borderTopLeftRadius: 25,
		borderTopRightRadius: 25,
		backgroundColor: "#fff",
	},
	thumb: {
		width: 120,
		height: 120,
		backgroundColor: "#F6F6F6",
		position: "absolute",
		top: -60,
		left: "50%",
		transform: [{translateX: -60}],
		borderRadius: 10,
	},
	input: {
		borderColor: "#E8E8E8",
		borderWidth: 1,
		padding: 16,
		margin: 16,
		boxSize: "border-box",
		backgroundColor: "#F6F6F6",
		borderRadius: 8,
		fontFamily: "Roboto",
		fontSize: 16,
		lineHeight: 19,
	},
	inputActive: {
		borderWidth: 1,
		padding: 16,
		margin: 16,
		boxSize: "border-box",
		borderRadius: 8,
		borderColor: "#FF6C00",
		backgroundColor: "#FFF",
	},
	title: {
		fontFamily: "Roboto",
		fontSize: 24,
		fontWeight: "bold",
		textAlign: "center",
		marginTop: 32,
		marginBottom: 16,
		fontSize: 30,
		lineHeight: 35,
		letterSpacing: 0.01,
	},
	buttonPrimary: {
		backgroundColor: "#FF6C00",
		borderRadius: 100,
		padding: 16,
		margin: 16,
		marginTop: 48,
		display: "flex",
		alignItems: "center",
	},
	buttonPrimaryText: {
		fontFamily: "Roboto",
		fontSize: 16,
		lineHeight: 19,
		color: "#fff",
	},
	buttonSecondary: {marginBottom: 140},
	buttonSecondaryText: {
		textAlign: "center",
		color: "#1B4371",
		fontFamily: "Roboto",
		fontSize: 16,
		lineHeight: 19,
	},
	inputContainer: {
		position: "relative",
	},
	passShower: {
		position: "absolute",
		right: 32,
		top: "50%",
		zIndex: 1,
		transform: [{translateX: 0}, {translateY: -10}],
	},
	passShowerText: {
		color: "#1B4371",
		fontSize: 16,
		lineHeight: 19,
	},
	thumbFile: {
		boxSize: "border-box",
		position: "absolute",
		top: 81,
		left: 107,
		flex: 1,
		zIndex: 1,
	},
});
